# Generated by Django 5.2.3 on 2025-06-12 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finledger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debtor',
            name='fullname',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='debtor',
            name='phone',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
