# Generated by Django 5.2.3 on 2025-06-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finledger', '0002_debtor_fullname_debtor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
